const a = 3 + 5;

try {
	console.log(b);
} catch (error) {
	console.log("Rudra is loggin");
} finally {
	console.log("Finally block");
}
